from typing import Tuple

CHARS_PER_TOKEN_ESTIMATE = 4
MAX_DIFF_TOKENS_DEFAULT = 16000  # ~64,000 characters ceiling
TRUNCATION_NOTE = "\n\n...[DIFF TRUNCATED: Exceeded MAX_DIFF_TOKENS guardrail to protect API token quota]...\n"

def cap_diff(diff: str, max_tokens: int = MAX_DIFF_TOKENS_DEFAULT) -> Tuple[str, bool]:
    """
    Bounds how much diff text reaches the LLM model to protect against
    accidental cost blowups from giant autogenerated files, lockfiles, or huge PRs.
    """
    max_chars = max_tokens * CHARS_PER_TOKEN_ESTIMATE

    if len(diff) <= max_chars:
        return diff, False

    return diff[: max_chars - len(TRUNCATION_NOTE)] + TRUNCATION_NOTE, True
